spring:
  application:
    name: API de controle ponto
  datasource:
    url: jdbc:mysql://localhost:3306/controle_ponto
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update




